Kraken/text input v7
NoRedInk/noredink-ui pull request #759
Opened 2021-10-28 02:08 UTC by tesk9

New version of TextInput that adds first class support for:
- Password input show/hide PW functionality
- Guidance that can be attached to the input when the error isn't showing

## For reviewer

Instead of looking at the whole diff, I recommend ignoring the first commit (see https://github.com/NoRedInk/noredink-ui/pull/759/files/f00b1a8e9b935eae76b46787d0802c44e6b8b217..c9da21b1cd1bb6901531ab4f5d10482ede096943). This will give you a much cleaner (although still large) view!

## Visual changes

(Note: I renamed `password` to `newPassword` in the styleguide -- see deploy preview for most-up-to-date version)

**With no guidance, no error message, and no chars**

<img width="1084" alt="" src="https://user-images.githubusercontent.com/8811312/139485441-6f7aecc8-d4ee-44a5-a43d-b3cd1736b05a.png">

**With guidance, no error message, and no chars**
<img width="1059" alt="" src="https://user-images.githubusercontent.com/8811312/139485448-cb94969d-7c58-4143-8b2a-4b3284efec4a.png">

**With guidance, error message, and no chars**
<img width="1070" alt="" src="https://user-images.githubusercontent.com/8811312/139485447-ef70cba0-7b09-413b-9ef1-f079294bbc0b.png">

**With guidance, no error message, and chars**
<img width="1071" alt="" src="https://user-images.githubusercontent.com/8811312/139485445-40e57df1-c593-4b59-a3b8-ecdd0d322d6e.png">

**With guidance, no error message, chars, and user hit "Show password"**
<img width="1065" alt="" src="https://user-images.githubusercontent.com/8811312/139485443-08c29dff-bd85-4e35-8046-db665cd3e613.png">

cc @NoRedInk/design 

## Accessibility notes

I looked around a bit online for instructions on show/hide password behavior. It seems like often folks use a checkbox or a "toggle" button. Both of these options seems strange to me since we're changing the text of the button from "Show" to "Hide".

Would love to talk through some options at some point! (I don't think this is blocking -- we should be able to merge & release and continue to iterate on the underlying implementation without changing the API) cc @krinhorn

2021-10-29 20:40 UTC, bendansby commented
Love it!

defaultMarginTop should be 5

2021-10-29 22:56 UTC, tesk9 commented
Sounds good! I think I'd prefer to change that in a separate release, because I know I did some sneaky shifting by pixel value in a couple places in the monolith (specifically related to the search input needing to be vertically aligned with other content)

2021-10-29 23:08 UTC, bendansby commented
Can we add padding to avoid password manager collision like we do for "Forgot?"

<img width="994" alt="image" src="https://user-images.githubusercontent.com/13528834/139510277-fce40f7a-e4a8-4e8c-8c17-930bd53fe46c.png">

2021-10-29 23:21 UTC, ap-nri commented
I can't review this right now because I'm on my phone but this rocks and you rock for making it. I am thrilled. I am a being of pure joy.

2021-11-01 19:23 UTC, tesk9 commented
Okay I looked at the "Forgot?" styles and it seems like the floating button is positioned the same distance from the righthand side. LastPass positions its little icon thing as a background with `background-position: 98% 50%`... I think the password managers will end up looking about the same in context. Although we could try setting a different background position with `important`?

`right: 15px` is used in both this component and on /log in:
<img width="494" alt="Screen Shot 2021-11-01 at 10 10 45 AM" src="https://user-images.githubusercontent.com/8811312/139728227-10c57852-6bdb-477d-a2ef-6fd632edad6d.png">
<img width="478" alt="Screen Shot 2021-11-01 at 10 10 11 AM" src="https://user-images.githubusercontent.com/8811312/139728231-70d35b53-0cde-4192-b56c-d6f936d26b0b.png">


Somewhat separately, I'm a little worried that `Show password` takes up too much room when the viewport or container is small, like in the log in header dropdown: 

![image](https://user-images.githubusercontent.com/8811312/139728961-688c25c5-660e-4e3e-8b41-27d0eed0e7c5.png)

2021-11-01 19:36 UTC, bendansby commented
You noted here that LastPass behaves differently from the other password managers; https://github.com/NoRedInk/NoRedInk/pull/35158#pullrequestreview-748301845

2021-11-01 21:13 UTC, tesk9 commented
<img width="1100" alt="Screen Shot 2021-11-01 at 2 12 25 PM" src="https://user-images.githubusercontent.com/8811312/139742882-e5faf412-051d-45fb-aec2-3445dc8f32af.png">


<img width="1102" alt="Screen Shot 2021-11-01 at 2 12 31 PM" src="https://user-images.githubusercontent.com/8811312/139742880-bef47501-6d17-4aa5-9118-c72bb030f225.png">

2021-11-01 22:08 UTC, bendansby commented
Thanks! I think the narrow input concern should be fine since even in the login dropdown it's wider than that, but we can see!

2021-11-01 22:30 UTC, tesk9 commented
Phew! I'm glad adding padding worked for 1password! I was confused for a while on this, thinking that you were asking me to shift the "Show PW" message further left, further squishening the visible characters. Thanks for sticking with me on this!

2021-11-02 18:01 UTC, ap-nri requested changes
one question

2021-11-02 18:05 UTC, ap-nri commented on src/Nri/Ui/TextInput/V7.elm
> +    , custom : List (Html.Attribute Never)
if so, then ready to FIRE AWAY

2021-11-02 18:06 UTC, ap-nri commented
I like the way this works out on Safari 15.1
![image](https://user-images.githubusercontent.com/75996561/139921032-ed31bce0-8401-4ac7-b8cc-b663ebfa30d0.png)

2021-11-02 19:17 UTC, tesk9 commented on src/Nri/Ui/TextInput/V7.elm
> +    , custom : List (Html.Attribute Never)
No, it wouldn't. I will add an onFocus attribute though!

2021-11-02 19:24 UTC, tesk9 commented on src/Nri/Ui/TextInput/V7.elm
> +    , custom : List (Html.Attribute Never)
Done 😄

2021-11-02 21:24 UTC, ap-nri commented
@tesk9 I'm pro merging now!! If you are too then here's your gif 

![](https://media.giphy.com/media/7TRowDsdWMf1uTNqfT/giphy-downsized.gif)

2021-11-02 23:02 UTC, merged